slangwords = {
    "@": "di",
    "abis": "habis",
    "wtb": "beli",
    "masi": "masih",
    "wts": "jual",
    "wtt": "tukar",
    "bgt": "banget",
    "maks": "maksimal",
    "btw": "ngomong-ngomong",
    "gk": "tidak",
    "tp": "tapi",
    "jg": "juga",
    "udh": "sudah",
    "ga": "tidak",
    "gue": "saya",
    "gua": "saya",
    "kalo": "kalau",
    "krn": "karena",
    "tdk": "tidak",
    "aja": "saja",
    "sm": "sama",
    "udh": "sudah",
    "yg": "yang",
    "dr": "dari",
    "muda": "mudah",
    "aku": "saya",
    "banget": "sangat",
    "yg": "yang",
    "aja": "saja",
    "ya": "iya",
    "udah": "sudah",
    "kalo": "kalau",
    "sih": "memang",
    "karna": "karena",
    "deh": "lah",
    "bgt": "sangat",
    "ku": "saya",
    "cuma": "hanya",
    "tau": "tahu",
    "pake": "pakai",
    "pas": "saat",
    "kan": "", 
    "bhs": "bahasa",
    "gitu": "seperti itu",
    "app": "aplikasi",
    "belajarnya": "belajar",
    "nggak": "tidak",
    "apk": "aplikasi",
    "makasih": "terima kasih",
    "makasi": "terima kasih",
    "trs": "lalu",
    "sm": "sama",
    "dgn": "dengan",
    "tp": "tapi",
    "krn": "karena",
    "dr": "dari",
    "dmn": "di mana",
    "lbh": "lebih",
    "ngerti": "mengerti",
    "bikin": "membuat",
    "liat": "melihat",
    "nonton": "menonton",
    "duh": "aduh",
    "lho": "loh",
    "deh": "", 
    "dong": "", 
    "kok": "",  
    "nih": "",  
    "sih": "", 
    "tuh": "", 
    "polll": "",
    "@": "di", 
    "abis": "habis", 
    "ad": "ada", 
    "adlh": "adalah", 
    "afaik": "as far as i know", 
    "ahaha": "haha", 
    "aj": "saja", 
    "duolingi" : "duolingo",
    "kalo": "kalau",
    "mgkin": "mungkin", "fav": "favorit",
    "thd": "terhadap", "thx": "terima kasih",
    "bcanda": "bercanda",
    "di pahami": "dipahami",
    "mentok": "maksimal",
    "update": "diperbarui",
    "please": "tolong",
    "plis": "tolong",
    "heart": "hati",
    "plss" : "tolong",
    "apk" : "aplikasi",
    "thanks" : "Terimakasih",
    "emg": "memang",
    "bgt": "banget",
    "bgd": "banget",
    "tp": "tapi",
    "jd": "jadi",
    "dr": "dari",
    "dri": "dari",
    "sm": "sama",
    "karna": "karena",
    "krn": "karena",
    "nya": "nya",
    "dg": "dengan",
    "dgn": "dengan",
    "yg": "yang",
    "gak": "tidak",
    "bs": "bisa",
    "aja": "saja",
    "aj": "saja",
    "udh": "sudah",
    "dah": "sudah",
    "nih": "ini",
    "yaa": "ya",
    "yaaa": "ya",
    "yaaaa": "ya",
    "sy": "saya",
    "sya": "saya",
    "syaa": "saya",
    "bnyk": "banyak",
    "trus": "terus",
    "kyak": "seperti",
    "kayak": "seperti",
    "aplgi": "apalagi",
    "sprti": "seperti",
    "k": "ke",
    "msk": "masuk",
    "tlp": "telepon",
    "tggu": "tunggu",
    "mash": "masih",
    "g": "tidak",
    "blm": "belum",
    "kmn": "kemana",
    "kpd": "kepada",
    "sll": "selalu",
    "bbrapa": "beberapa",
    "smg": "semoga",
    "lg": "lagi",
    "jugaa": "juga",
    "krg": "kurang",
    "tmpt": "tempat",
    "trmsuk": "termasuk",
    "dikit" : "sedikit",
    "cu": "kamu",
    "bro": "saudara",
    "sis": "saudari",
    "yuk": "ayo",
    "ntar": "nanti",
    "udah": "sudah",
    "sama": "sama",
    "lho": "loh",
    "bosen": "bosan",
    "emang": "memang",
    "ngomong": "berbicara",
    "keren": "keren",
    "asik": "asik",
    "seru": "seru",
    "seru banget": "sangat seru",
    "kepo": "penasaran",
    "gemes": "gemas",
    "membatu" : "membantu",
    "dgn" : "dengan",
    "dngan" : "dengan",
    "overall" : "sejauh ini",
    "bagu" : "bagus",
    "bgs" : "bagus",
    "bags" : "bagus",
    "bgus" : "bagus",
    "ikln"  : "iklab",
    "free" : "gratis",
    "susa" : "susah",
    "basic" : "dasar",
    "yg":"yang",
    "yng": "yang",
    "bagusss": "bagus",
    "ny" : "nya",
    "baguss": "bagus",
    "bljr" : "belajar",
    "ank" : "anak",
    "cpt" : "cepat",
     "aku": "saya",
    "nya": "",         # kata ganti milik, bisa dihapus/ditransformasikan tergantung konteks
    "banget": "sangat",
    "yg": "yang",
    "buat": "untuk",
    "apk": "aplikasi",
    "ya": "iya",
    "gak": "tidak",
    "aja": "saja",
    "ga": "tidak",
    "udah": "sudah",
    "kalo": "kalau",
    "sih": "",         # partikel penguat, biasanya tidak dibutuhkan
    "karna": "karena",
    "bikin": "membuat",
    "deh": "",         # partikel, bisa diabaikan
    "bgt": "banget",   # bisa jadi "sangat"
    "ku": "saya",
    "dong": "",        # partikel persuasi
    "loh": "",         # partikel
    "punya": "memiliki",
    "nggak": "tidak",
    "mo": "mau",
    "biar": "agar",
    "nonton": "menonton",
    "ngegame": "bermain game",
    "denger": "mendengar",
    "liat": "melihat",
    "ngerti": "mengerti",
    "sampe": "sampai",
    "emang": "memang",
    "tuh": "",         # partikel
    "ntar": "nanti",
    "temen": "teman",
    "cemungudh": "semangat",
    "makasih": "terima kasih",
    "ngulang": "mengulang",
        "btw": "ngomong-ngomong",
    "tolongin": "tolong",
    "tq": "terima kasih",
    "makasi": "terima kasih",
    "gpp": "tidak apa-apa",
    "pdhl": "padahal",
    "tdk": "tidak",
    "bisa2": "bisa-bisa",
    "app": "aplikasi",
    "apps": "aplikasi",
    "playstore": "toko aplikasi",
    "game": "permainan",
    "crash": "macet",
    "bug": "kesalahan",
    "update": "pembaruan",
    "version": "versi",
    "level": "tingkatan",
    "account": "akun",
    "login": "masuk",
    "logout": "keluar",
    "feature": "fitur",
    "feedback": "masukan",
    "support": "dukungan",
    "score": "skor",
    "point": "poin",
    "rank": "peringkat",
    "task": "tugas",
    "reward": "hadiah",
    "ads": "iklan",
    "free": "gratis",
    "premium": "berbayar",
    "challenge": "tantangan",
    "language": "bahasa",
    "learn": "belajar",
    "learning": "pembelajaran",
    "daily": "harian",
    "goal": "tujuan",
    "reset": "atur ulang",
    "notification": "notifikasi",
    "reminder": "pengingat",
    "timer": "pengatur waktu",
    "loading": "memuat",
    "slow": "lambat",
    "fast": "cepat",
    "error": "kesalahan",
    "trs": "terus",
    "bbrp": "beberapa",
    "sm": "sama",
    "tp": "tapi",
    "dr": "dari",
    "sy": "saya",
    "dy": "dia",
    "mrk": "mereka",
    "jd": "jadi",
    "bljr": "belajar",
    "dl": "dulu",
    "skrg": "sekarang",
    "bsk": "besok",
    "kmrn": "kemarin",
    "krn": "karena",
    "krg": "kurang",
    "dpt": "dapat",
    "cmn": "cuma",
    "lg": "lagi",
    "smg": "semoga",
    "trs2": "terus-terusan",
    "knp": "kenapa",
    "gmn": "gimana",
    "gitu": "begitu",
    "utk": "untuk",
    "udh": "sudah",
    "blm": "belum",
    "bkn": "bukan",
    "td": "tadi",
    "nyoba": "mencoba",
    "nanya": "bertanya",
    "ngasi": "memberi",
    "ngejelasin": "menjelaskan",
    "mending": "lebih baik",
    "lumayan": "cukup",
    "cape": "lelah",
    "capek": "lelah",
    "ngulangin": "mengulang",
    "nyambung": "terhubung",
     "lol": "lucu sekali",
    "omg": "ya ampun",
    "idk": "saya tidak tahu",
    "imo": "menurut saya",
    "imho": "menurut saya secara rendah hati",
    "pls": "tolong",
    "plz": "tolong",
    "u": "kamu",
    "ur": "punyamu",
    "r": "adalah",
    "thx": "terima kasih",
    "thanx": "terima kasih",
    "np": "tidak masalah",
    "btw": "ngomong-ngomong",
    "fyi": "sebagai informasi",
    "asap": "secepatnya",
    "wtf": "apa-apaan ini",
    "lmao": "tertawa terbahak-bahak",
    "brb": "sebentar ya",
    "afaik": "setahu saya",
    "bcs": "karena",
    "bc": "karena",
    "tbh": "sejujurnya",
     "bljr": "belajar",
    "duolinggo": "duolingo",  # salah ketik umum
    "baguss": "bagus",
    "baguuuus": "bagus",
    "mantapp": "mantap",
    "mantul": "mantap betul",
    "mantaap": "mantap",
    "ok": "oke",
    "okee": "oke",
    "okey": "oke",
    "kerenzz": "keren",
    "kerenn": "keren",
    "kereen": "keren",
    "edukatifff": "edukatif",
    "seruuu": "seru",
    "seruuuu": "seru",
    "sipp": "sip",
    "sipp banget": "sangat bagus",
    "recommended": "direkomendasikan",
    "recomended": "direkomendasikan",
    "rekomended": "direkomendasikan",
    "worthit": "layak dicoba",
    "worth it": "layak dicoba",
    "topmarkotop": "sangat bagus",
    "josss": "hebat",
    "thebest": "terbaik",
    "the best": "terbaik",
    "very good": "sangat bagus",
    "helpfull": "membantu",
    "funny": "menyenangkan",
    "amazing": "luar biasa",
    "great": "bagus",
    "lovee": "suka",
    "lovely": "menyenangkan",
    "engaging": "menarik",
    "usefull": "berguna",
    "easy": "mudah",
    "fun": "menyenangkan",
    "lemot": "lambat",
    "lelet": "lambat",
    "crash": "macet",
    "ngelag": "lambat",
    "laggy": "lambat",
    "not responding": "tidak merespons",
    "gagal login": "tidak bisa masuk",
    "gabisa": "tidak bisa",
    "ga bisa": "tidak bisa",
    "nggak bisa": "tidak bisa",
    "gajelas": "tidak jelas",
    "ribet": "sulit",
    "susah": "sulit",
    "ngehang": "macet"
}